# Generated by Django 5.0.7 on 2024-07-19 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_categoria'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('lancamento', models.DateField()),
                ('descricao', models.TextField()),
                ('disponivel', models.BooleanField(default=True)),
                ('autores', models.ManyToManyField(to='biblioteca.autores')),
                ('capa', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image')),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.categoria', verbose_name='categoria')),
                ('generos', models.ManyToManyField(to='biblioteca.generos')),
            ],
        ),
    ]
