# Generated by Django 5.0.7 on 2024-08-04 15:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='passage_id',
            field=models.CharField(default=uuid.UUID('7f91aad5-3dfe-4b2b-b05b-744afdb85f93'), max_length=255, unique=True),
        ),
    ]
