# Generated by Django 5.0.7 on 2024-08-30 19:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_passage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='passage_id',
            field=models.CharField(default=uuid.UUID('5a9b9995-90f1-4170-bc9d-30f77797e450'), max_length=255, unique=True),
        ),
    ]
