# Generated by Django 5.0.7 on 2024-08-22 22:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_passage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='passage_id',
            field=models.CharField(default=uuid.UUID('1161a6df-1ec0-4176-9d9e-7226166b0e05'), max_length=255, unique=True),
        ),
    ]
