# Generated by Django 5.0.7 on 2024-09-02 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_usuario_user_meta_usuario_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user_meta',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
