# Generated by Django 5.0.7 on 2024-09-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_remove_usuario_user_meta_remove_usuario_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='passage_id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='age',
            field=models.IntegerField(default=1, verbose_name='your age'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
