# Generated by Django 5.0.7 on 2024-09-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_remove_usuario_passage_id_usuario_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='age',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
