# Generated by Django 5.0.7 on 2024-09-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_usuario_has_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='age',
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
