# Generated by Django 5.0.7 on 2024-09-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_usuario_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='account_type',
            field=models.IntegerField(choices=[(0, 'ADULTO'), (1, 'INFANTOJUVENIL'), (2, 'INFANTIL')], default=0),
        ),
    ]
