from .categoria import CategoriaViewSet
from .genero import GeneroViewSet
from .autores import AutoresViewSet
from .livro import LivroViewSet
from .livroPego import LivroPegoViewSet
from .avaliacao import AvaliacaoViewSet
from .favorito import FavoritoViewSet
from .relatorio import GeneratePDFView
from .taxas import TaxasViewSet
