<<<<<<<< HEAD:core/biblioteca/migrations/0003_categoria.py
# Generated by Django 5.0.7 on 2024-07-15 17:11
========
# Generated by Django 5.0.7 on 2024-07-19 19:27
>>>>>>>> 37c33f17d7d2a90ae218c495d45fc0611aa67fe5:core/biblioteca/migrations/0001_initial.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_autores'),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<<< HEAD:core/biblioteca/migrations/0003_categoria.py
            name='Categoria',
========
            name='Autores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Generos',
>>>>>>>> 37c33f17d7d2a90ae218c495d45fc0611aa67fe5:core/biblioteca/migrations/0001_initial.py
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
    ]
