# Generated by Django 5.0.7 on 2024-09-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_alter_livro_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='livropego',
            name='data_devolucao',
            field=models.DateField(default=None),
        ),
    ]
