# Generated by Django 5.0.7 on 2024-09-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_blockedlivros'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedlivros',
            name='Categoria',
            field=models.ManyToManyField(related_name='blocked_livros', to='biblioteca.categoria'),
        ),
        migrations.AddField(
            model_name='blockedlivros',
            name='Generos',
            field=models.ManyToManyField(related_name='blocked_livros', to='biblioteca.generos'),
        ),
    ]
