# Generated by Django 5.0.7 on 2024-09-11 00:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_blockedlivros_categoria_blockedlivros_generos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.ManyToManyField(related_name='familias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
