# Generated by Django 5.0.7 on 2024-09-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0011_familia'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='nome',
            field=models.CharField(default='Familia', max_length=80),
        ),
    ]
