# Generated by Django 5.0.7 on 2024-09-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0014_alter_categoria_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='livropego',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
